-- Table: coached_invoices
-- Stores paid invoices for coached clients (from Stripe Connect invoice.paid webhook).
-- Used to display and download invoices per user from the profile.

create table public.coached_invoices (
  id bigint generated by default as identity primary key,
  stripe_invoice_id text not null,
  organization_id bigint not null references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  buyer_email text,
  amount_cents integer not null,
  currency text not null default 'eur',
  invoice_pdf_url text,
  status text not null default 'paid',
  stripe_created_at timestamptz,
  created_at timestamptz not null default now(),

  constraint coached_invoices_stripe_invoice_id_key unique (stripe_invoice_id)
);

-- Index for listing by user or by email (profile page)
create index idx_coached_invoices_user_id on public.coached_invoices(user_id);
create index idx_coached_invoices_buyer_email on public.coached_invoices(buyer_email);

-- Index for idempotent webhook upsert by stripe_invoice_id (unique already covers this)
create index idx_coached_invoices_stripe_invoice_id on public.coached_invoices(stripe_invoice_id);

comment on table public.coached_invoices is 'Invoices for coached clients, synced from Stripe Connect invoice.paid';

-- RLS: users can only read their own invoices
alter table public.coached_invoices enable row level security;

create policy "coached_invoices_select_own"
  on public.coached_invoices
  for select
  using (
    user_id = auth.uid()
    or (
      buyer_email is not null
      and lower(buyer_email) = lower((auth.jwt() ->> 'email'))
    )
  );

-- Inserts/updates come only from the webhook (service role), so no policy for insert/update for authenticated.
